# Включение/отключение функций
features:
  join-message: true # Включить/Отключить сообщение при входе игрока на сервер.
  quit-message: true # Включить/Отключить сообщение при выходе игрока с сервера.
  join-particles: true # Включить/Отключить партиклы при входе игрока на сервер.
  quit-particles: true # Включить/Отключить партиклы при выходе игрока с сервера.

# Настройки сообщений
messages:
  join: "&#00ff00[+] %player% присоединился к серверу" # Есть поддержка &#rrggbb и &
  quit: "&#ff0000[-] %player% покинул сервер" # Есть поддержка &#rrggbb и &

# Настройки частиц, брать из сайта https://helpch.at/docs/1.16.5/org/bukkit/Particle.html
particles:
  join: # Партиклы при входе игрока на сервер
    type: HEART
    count: 20
  quit: # Партиклы при выходе игрока с сервера
    type: PORTAL
    count: 15
